// examples/nuxt-app/app.vue
<template>
  <div class="container">
    <h1>📦 Bundle Watch + Nuxt</h1>
    <p class="time">{{ formattedTime }}</p>
    <p class="description">{{ data }}</p>
    <div class="card">
      <p>This Nuxt app uses Bundle Watch via the Vite plugin!</p>
      <p>Check <code>bundle-report/index.html</code> after building.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { format } from 'date-fns';
import axios from 'axios';

const time = ref(new Date());
const data = ref('Loading...');

const formattedTime = computed(() => format(time.value, 'PPpp'));

onMounted(() => {
  setInterval(() => {
    time.value = new Date();
  }, 1000);

  axios.get('https://api.github.com/repos/anthropics/claude-code')
    .then(res => data.value = res.data.description)
    .catch(() => data.value = 'Bundle Watch + Nuxt Example');
});
</script>

<style scoped>
.container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  background-color: #0f172a;
  color: #e2e8f0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

h1 {
  font-size: 3rem;
  margin: 0 0 1rem;
}

.time {
  font-size: 1.5rem;
  margin: 0 0 2rem;
  color: #94a3b8;
}

.description {
  font-size: 1.1rem;
  color: #cbd5e1;
  margin-bottom: 2rem;
}

.card {
  background: #1e293b;
  padding: 2rem;
  border-radius: 0.5rem;
  border: 1px solid #334155;
  max-width: 600px;
  text-align: center;
}

code {
  background: #0f172a;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
}
</style>

// examples/webpack-app/src/App.tsx
import axios from 'axios';
import classNames from 'classnames';
import { format, formatDistance } from 'date-fns';
import { chunk, sortBy, uniq } from 'lodash';
import { useEffect, useState } from 'react';

export default function App() {
  const [currentTime, setCurrentTime] = useState(new Date());
  const [data, setData] = useState<string[]>([]);

  useEffect(() => {
    // Update time every second
    const timer = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);

    // Simulate fetching data
    const fetchData = async () => {
      try {
        const response = await axios.get('https://api.github.com/repos/anthropics/claude-code');
        setData(uniq([response.data.name, response.data.description]));
      } catch (_error) {
        console.log('Demo mode - API not called');
        setData(['Bundle', 'Watch', 'Example']);
      }
    };

    fetchData();
    return () => clearInterval(timer);
  }, []);

  // Use lodash to chunk data
  const chunkedData = chunk(data, 2);
  const sortedData = sortBy(data, (d: string) => d.length);

  const containerClass = classNames('container', { 'has-data': data.length > 0 });

  return (
    <div style={styles.container} className={containerClass}>
      <h1 style={styles.title}>📦 Bundle Watch</h1>
      <p style={styles.subtitle}>Webpack + Bundle Watch Example</p>
      <p style={styles.description}>This app is built with Webpack and analyzed by Bundle Watch!</p>

      <div style={styles.info}>
        <p>Current time: {format(currentTime, 'PPpp')}</p>
        <p>Time ago: {formatDistance(new Date(2024, 0, 1), currentTime, { addSuffix: true })}</p>
        {data.length > 0 && (
          <>
            <p>Data chunks: {chunkedData.length}</p>
            <p>Sorted items: {sortedData.join(', ')}</p>
          </>
        )}
      </div>
    </div>
  );
}

const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  title: {
    fontSize: '3rem',
    margin: '0 0 1rem',
    color: '#333',
  },
  subtitle: {
    fontSize: '1.5rem',
    margin: '0 0 2rem',
    color: '#666',
  },
  description: {
    fontSize: '1.1rem',
    color: '#888',
  },
  info: {
    marginTop: '2rem',
    padding: '1.5rem',
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
};
